INSERT INTO produse (nume, pret, gramaj, imagine) VALUES 
    ('Cârciumărese Uriașe Melanj', 3.99, 1.8, 'carciumarese.jpg'),
    ('Clopoței Melanj', 4.99, 1.2, 'clopotei.jpg'),
    ('Condurul Doamnei Melanj', 4.99, 0.8, 'condurul_doamnei.jpg'),
    ('Crăițe Pitice Melanj', 5.99, 2, 'craite_pitic.jpg'),
    ('Creasta Cocoșului Melanj', 2.99, 0.75, 'creasta_cocosului.jpg'),
    ('Floarea Pasiunii Melanj', 6.99, 1.75, 'floarea_pasiunii.jpg'),
    ('Flori De Piatra Melanj', 3.99, 1.5, 'flori_de_piatra.jpg'),
    ('Garofița De Grădină Melanj', 4.99, 2.0, 'garofita_de_gradina.jpg'),
    ('Margarete Melanj', 4.99, 2.0, 'margarete.jpg'),
    ('Mușcate Melanj', 4.99, 1.5, 'muscate.jpg'),
    ('Noptițe Melanj', 6.99, 2.2, 'noptite.jpg'),
    ('Nu mă uita Melanj', 3.99, 1.25, 'nu_ma_uita.jpg'),
    ('Ochiul Boului Pitic Melanj', 4.99, 2.0, 'ochiul_boului_pitic.jpg'),
    ('Panseluțe Melanj', 4.99, 1.75, 'panselute.jpg'),
    ('Petunie Curgătoare Melanj', 4.99, 2.0, 'petunia_curgatoare.jpg'),
    ('Pufuleți Albastru Melanj', 2.99, 1.0, 'pufuleti_albastru.jpg'),
    ('Scateiuță Melanj', 3.99, 1.25, 'scanteiuta.jpg'),
    ('Zorele Pitice Melanj', 4.99, 1.75, 'zorele_pitice.jpg'),
    ('Regina Nopții Melanj', 3.99, 1.25, 'regina_noptii.jpg'),
    ('Gazania Melanj', 4.99, 1.75, 'gazania.jpg');
